services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  cachet:
    build:
      context: .
      args:
        - cachet_ver=3.x
    ports:
      - 80:8000
    links:
      - postgres:postgres
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - APP_KEY=${APP_KEY:-null}
      - LOG_CHANNEL=stderr
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=false
      - CACHE_STORE=database
      - SESSION_DRIVER=database
      - QUEUE_CONNECTION=database
      - DEBUG=false
    depends_on:
      - postgres
    restart: on-failure
