apiVersion: v1
kind: DeploymentConfig
metadata:
  name: cachet
  labels:
    app: cachet
  annotations:
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources:
  triggers:
    -
      type: ConfigChange
  replicas: 1
  test: false
  selector:
    app: cachet
    deploymentconfig: cachet
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cachet
        deploymentconfig: cachet
      annotations:
    spec:
      containers:
        -
          name: cachet
          image: cachethq/docker:3.x
          ports:
            -
              containerPort: 8000
              protocol: TCP
          env:
            -
              name: APP_ENV
              value: nonProd
            -
              name: APP_DEBUG
              value: 'true'
            -
              name: APP_URL
              value: 'https://status.example.com'
            -
              name: APP_KEY
              value: 'base64:KEY'
            -
              name: DB_CONNECTION
              value: pgsql # pgsql, mysql, mariadb, or sqlite
            -
              name: DB_HOST
              value: db_hostname
            -
              name: DB_DATABASE
              value: cachethq
            -
              name: DB_USERNAME
              value: cachethq
            -
              name: DB_PASSWORD
              value: mypassword
            -
              name: DB_PORT
              value: '5432'
            -
              name: CACHE_STORE
              value: database
            -
              name: SESSION_DRIVER
              value: database
            -
              name: QUEUE_CONNECTION
              value: database
            -
              name: CACHET_EMOJI
              value: 'false'
            -
              name: MAIL_MAILER
              value: smtp
            -
              name: MAIL_HOST
              value: smtp.hostname.com
            -
              name: MAIL_PORT
              value: '25'
            -
              name: MAIL_USERNAME
              value: 'null'
            -
              name: MAIL_PASSWORD
              value: 'null'
            -
              name: MAIL_FROM_ADDRESS
              value: 'null'
            -
              name: MAIL_FROM_NAME
              value: 'null'
            -
              name: MAIL_ENCRYPTION
              value: 'null'
            -
              name: REDIS_HOST
              value: 'null'
            -
              name: REDIS_DB
              value: 'null'
            -
              name: REDIS_PORT
              value: 'null'
          resources:
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 1001
status:
